server:
  port: 9091

spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/vk-community-intersection-config

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
